bix_category_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: BixCategoryBundle:Default:index }
    
bix_category_prova:
    pattern:  /prova
    defaults: { _controller: BixCategoryBundle:Default:prova }
    
BixCategoryBundle_category:
        resource: "@BixCategoryBundle/Resources/config/routing/category.yml"
        prefix:   /admin/category
