parameters:
#    bix_category.example.class: Bix\CategoryBundle\Example

services:
#    bix_category.example:
#        class: %bix_category.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
