acme_prova_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeProvaBundle:Default:index }
    
    
acme_prova_testcat:
    pattern:  /testcat
    defaults: { _controller: AcmeProvaBundle:Category:index }
