# sg_category:
#     resource: "@SgCategoryBundle/Resources/config/routing.yml"
#     prefix:   /admin/category

sg_main:
    resource: "@SgMainBundle/Resources/config/routing.yml"
    prefix:   /

sg_user:
    resource: "@SgUserBundle/Resources/config/routing.yml"
    prefix:   /

sg_category:
    resource: "@SgCategoryBundle/Resources/config/routing.yml"
    prefix:   /