sg_category_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SgCategoryBundle:Default:index }

#Qui vanno importate a mano le rotte di BixCategoryBundle
sg_category_prova:
    pattern:  /prova
    defaults: { _controller: SgCategoryBundle:Default:prova }

category_new:
    pattern: category/new
    defaults: { _controller: BixCategoryBundle:Category:new }

category_index:
    pattern: category/index
    defaults: { _controller: BixCategoryBundle:Category:index }

category_menu:
    pattern: category/menu
    defaults: { _controller: BixCategoryBundle:Category:catMenu }