parameters:
#    sg_category.example.class: Sg\CategoryBundle\Example

services:
#    sg_category.example:
#        class: %sg_category.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
